### ISSUE TITLE
Infinite death

### ISSUE THREAD

**Issue by H077y** [Ravethn/Slughost#16]
I have no idea what triggers this to happen. I have tested this by removing the mod, and it does not happen.\
The main thing to look at in the video is the top right corner when I pause, which displays a kill feed. It says that the player died **a lot** of times which freezes my game.

https://github.com/user-attachments/assets/a520269c-22e8-49eb-8fef-45a2b61ae2da

**Comment by Ravethn** [comment]
I think it's the ghost for the player spawning over and over again and instantly dying from the pit probably

**Comment by H077y** [comment]
Yeah that's what I figured
